apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kas-fleetshard-operator.0.4.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Managed Kafka
      displayName: Managed Kafka
      kind: ManagedKafka
      name: managedkafkas.managedkafka.bf2.org
      version: v1alpha1
    - description: Managed Kafka Agent
      displayName: Managed Kafka Agent
      kind: ManagedKafkaAgent
      name: managedkafkaagents.managedkafka.bf2.org
      version: v1alpha1
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAINElEQVR4Xu1aW2wcVxn+zszs7NXuruNb6rTddbJ1Lo6TJkgJpCR2RVQLqWklRKEPiBR4RKpVJJCQUCvRV0hQH5B4oUj0QkRVHCpwKMJJANE+2E4ciN3EySZ2EmftOL7tendnd+agM3uxxzuzO7MXsOI9kpVo5j//f/7vv58dgk2+yCbXHzUAah6wyRGohcAmd4BaEtxUIRDq6+0OnB44v9brNwUAob5ePwX9NYDu9tPnNDo/0gCE+rq9CuxvEKAva/VNA0Cor/ckhXIKIN61Lv/IA8DinIKeArBfr8I9sgCwOFdATxHgpUKlfcMAQAfhBe/YB6p0g5Du3KGpajmN24IgnbkpLgHkEhT5MulJXmKPWJwD4mtUjXOtuxfzAAba/zQJ0kHbfnDct5G2kr/MJmxh+Ubb8NzV9k6a4pvN8mIesDY5Vh0A1dKcnSnNMnG5Sqt6KkkB4U87EX+gdRQzIBCCPkrpm1lvqRoAacXF1wDCFLd+UgNtpEUPpv++D0rSZkbfojRVAYBeFF8CJazxqJjiTJNSlCeiDCrxhkBUFAA6/OUmCPVnsDLejcSdouhbIbCqPOEU2BqXIDYvIfLvJ6sPAB0+fgKi+11Q4gFNAgvnof5boTU1cBipmMMUN8EXhX3rPBgIbFUdADra+zqI82ea08WuA+yvAmt+zI+F8eL5U2xZhOOJB1Di2vxQVQB0lc8qzbxAWSkLApbxp84dKpj0iJhEXecUxKYlyJINydk6jcyqAVBQeXaEZBhYHioLgMjtVswO7zTkYW+bg2f3PRBOVmmqBsDnv29/PSlxWjcvolp9nRNPbHkAJB+WDAKr9yvTjbr7ne0zcAfvad5VDQAmZeyDwLCs8M+Y1SbYEYTIS8DiP8xuyaMzSn68JwHvF6/lLJ/daBGARUtl8PqZwIlEiu83o01zsw9NLdvSpCtXgfgtM9vyaEIfrY4Ja1/WH7wBsXE5j94aAPSCJQCYtNv9O6eWo6mMZvo68TyHYEcHeF5IE5RRFo0A8B29Ct4plQkA+i0BwGq9RIX+mxM3IMvpGqu3Ht/WCp+vSfuKeQDzBIvr7t++oHaA61fj8+owmA9ATETyoZbeqAoQkFetAXDlhWlAaJ0N38HMzLzuAdwuEf7tHfpqllAWjZLgluNX8uKfCU0uOyEvOVflKxwiV/UdloAETANAR59/G8T1/SznG9fGEU9oOz3m+v7AU3A48y2m7kvNAUufWfIBozJolAMSM/WgyUzoMUAW3Ejc2aIjk/ym/fTASVMA0E/3B+HxD6ttbmbJcgr3705iORJTw4GVvKaWVmPlsxsjQ4AUNg2C2ggNHIaSWlWKbdarAoxGCtdrrB+d2Ko7DDHrB04P3MoBMP6+v9/jTJxo8+nUbM4FPHYEIBUYQVlnyELBwlq514jwZ515O1jrW9c1qYYCpRykWTaGZIBSOMRuN0KO5s8PDYds8L7ysap7DoAr7+2g7EF74wxc9kT+8ZxBgP1l1vitGEbGo9iz3YWuoMuCOkj3BfKSpT2zQ7sQmWzJ28M8wRm4n1aFaaBwSC45Ic14dS3vCQpoOipEyd5+1ZvzAHDb4wg0zuofztsDcE4oCsVPf3UHyZSKGX783Ta4nMYzdx6zEisCywdzozvywsEskszyj3XaWFkeIV0fH9AA8J/3tk8oINvZQxYGPlc0n699G+DuQkqmePOXU7n3P/pOG+pcFgAoIRlmhaVWHJgfC+h6gxEQjlYOvgMiHFu5NIkS/yPZ9+cTGgDG3g+cT1H+GHso8ikEW6ZB9FJkw1dVHsNjUfzr8jKe2eXGl/Zppy9TFnn4J1NkRkQsOa4sPItYWIA0p0B6uNqXiA0cBA9RFXb7BfX/miVH3yL7//ITDQBs2JHWDDvNdUtorl/UbmTJ0KvfmlrWpkwAVHkZY1iWLS3vJgf/OqYB4PqZ1qaE7LpCKZfLNE+3TEMUUqv81yVCy4LXbqgEAL7jJVQmeYLsPZvL5hrfmPjwySOSxL8t0/TE53WtYJtvDmCWt7dpqkBZyrMKUMaEmJNdfwgQ9JqcAqejsR+QroGfZyl0GyH1ctPWEAI4d1mKGm2W7gKRy+Wzdu0GHMWvylYFyWGy92zrWsGGnSAd6TkCof5cVUCIjqIit8ZiC+A5aB7IddbX5AA9LnToK7tgc7wLYjN9CVL0NGw0nv+kKJlpgkxvUpxeG/sFQ2A9s/Tdn/hDgM9vxYpL1lJU8LZYZZzpTYoeIxl5kRz45Ox6OlPDUHaTevfPC98DJz5XUmgoMWBhsOhZLROY8AKy9yNdXS0BsPZgao4gtl5wnB8Q9oBwjxf1EIuToGkgbA1A3eGC5BUHwEga6yckxXOTKtBcCvCcPLLrmyG1/6YXRPbr7Bt5PBTSQ3rihqNiId47t96bBPCi0bnIsURlPcBI0PgH/rMpRXhh/XuHXXp2x9cm/0kHHX5wdETnh9ML5FiiYJtpxFvkkruDLeEYOBr6vwLAGql4Qsy7A7fxyd92fOP2tzLWfwcg7HsB7VJIgPQYXx2b423/g4EXGIJbcg7QQ3rsd+1Dssypbp4rMwRRkY8Egi/fn6WDjm5wVC8L/oIcS+Q+Zaswb6AAuBUD4NqH/pNSQmDfBGiWaJPfevrrIXXyohftg6BY7+aLUBJ+0oMFI/c1+lVKw/uCnYWV3pdhBcGtCAAsOSUV16iicNo2kyjhPa/cVJ/Ri46ToOrXmtpFyKvkaPydQkm1ZN5AUXArAkDB+rPBX9YA2OAGqvrxah5QdYg3uICaB2xwA1X9eDUPqDrEG1xAzQM2uIGqfrxN7wH/BYfgN7kt5RZpAAAAAElFTkSuQmCC
    mediatype: image/png
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: kas-fleetshard-operator
        rules:
        - apiGroups:
            - "apiextensions.k8s.io"
          resources:
            # the Java operator SDK seems to need listing CRDs
            - 'customresourcedefinitions'
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - managedkafka.bf2.org
          resources:
            # operator main custom resources for getting Kafka instance to deploy, configuration and reporting back status
            - managedkafkas
            - managedkafkas/status
            - managedkafkaagents
            - managedkafkaagents/status
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
        - apiGroups:
            - kafka.strimzi.io
          resources:
            # operator creates Kafka custom resource for Strimzi operator and gets the status
            - kafkas
            - kafkas/status
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
        - apiGroups:
            - apps
            - extensions
          resources:
            # operator creates Deployments for canary and admin server UI
            - deployments
            - deployments/status
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
        - apiGroups:
            - ""
          resources:
            # the operator creates Services for admin server UI
            - services
            # the operator creates ConfigMaps and Secrets for Kafka metrics configuration and TLS and Keycloak certificates
            - configmaps
            - secrets
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
        - apiGroups:
            - route.openshift.io
          resources:
            # the operator creates a Route for the admin server UI
            - routes
            - routes/custom-host
            - routes/status
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
      - serviceAccountName: kas-fleetshard-sync
        rules:
        - apiGroups:
            - managedkafka.bf2.org
          resources:
            # sync resources for getting Kafka instance to deploy, configuration and reporting back status
            - managedkafkas
            - managedkafkas/status
            - managedkafkaagents
            - managedkafkaagents/status
          verbs:
            - get
            - list
            - watch
            - create
            - delete
            - patch
            - update
        - apiGroups:
            - ""
          resources:
            # sync has to create namespaces for Kafka instances to deploy
            - namespaces
          verbs:
            - get
            - list
            - create
            - delete
            - update
      permissions:
      - serviceAccountName: kas-fleetshard-sync
        rules:
        - apiGroups:
            - ""
          resources:
            # sync needs to access Secret that stores the add-on parameters
            - secrets
          verbs:
            - get
            - list
            - watch
      deployments:
      - name: kas-fleetshard-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kas-fleetshard-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: kas-fleetshard-operator
            spec:
              containers:
              - image: quay.io/mk-ci-cd/kas-fleetshard-operator@sha256:7fd2aa2e2607688e1cca25a610e6331c455f0d9757688858965d7e39d1688615
                name: kas-fleetshard-operator
                env:
                - name: QUARKUS_PROFILE
                  value: prod
                - name: ADMINSERVER_CORS_ALLOWLIST
                  value: "(https?:\\/\\/localhost(:\\d*)?)|(https:\\/\\/(qaprodauth\\.)?cloud\\.redhat\\.com)|(https:\\/\\/(prod|qa|ci|stage)\\.foo\\.redhat\\.com:1337)"
                - name: KAFKA_EXTERNAL_CERTIFICATE_ENABLED
                  value: 'false'
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                resources:
                  limits:
                    cpu: 1500m
                    memory: 1Gi
                  requests:
                    cpu: 500m
                    memory: 512Mi
                volumeMounts:
                - mountPath: /config
                  name: logging-config-volume
                  readOnly: false
                  subPath: ""
              serviceAccountName: kas-fleetshard-operator
              volumes:
              - configMap:
                  defaultMode: 384
                  name: operator-logging-config-override
                  optional: true
                name: logging-config-volume
      - name: kas-fleetshard-sync
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kas-fleetshard-sync
          strategy: {}
          template:
            metadata:
              labels:
                name: kas-fleetshard-sync
            spec:
              containers:
              - image: quay.io/mk-ci-cd/kas-fleetshard-sync@sha256:3f3027a744f8535c31b9927764965eeafdf831286c56c8b914d7ca3829814241
                name: kas-fleetshard-sync
                env:
                - name: QUARKUS_PROFILE
                  value: prod
                - name: QUARKUS_KUBERNETES_CONFIG_ENABLED
                  value: "false"
                - name: SSO_ENABLED
                  value: "false"
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 256Mi
                  requests:
                    cpu: 100m
                    memory: 128Mi
                volumeMounts:
                - mountPath: /config
                  name: logging-config-volume
                  readOnly: false
                  subPath: ""
              serviceAccountName: kas-fleetshard-sync
              volumes:
              - configMap:
                  defaultMode: 384
                  name: sync-logging-config-override
                  optional: true
                name: logging-config-volume
  description: Operator That Manages Kafka Instances
  displayName: Operator That Manages Kafka Instances
  keywords:
  - managed
  - kafka
  maintainers:
  - email: help@redhat.com
    name: RedHat
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard
  version: 0.4.0
  replaces: kas-fleetshard-operator.0.3.2
