apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator.v0.23.0-1
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/k_wall/strimzi-operator@sha256:9b1afb1631e6c8425c97f3b02fa29d87f0f55bc09bf17cf662910665955da215
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.7.0=quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.7.0=quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
              value: |
                2.7.0=quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.7.0=quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.7.0=quay.io/k_wall/kafka-27@sha256:ffeba374a0e08ceccf91ad4459621942f63f8bf9ec63b4d2c2b34703f7fba939
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/k_wall/strimzi-operator@sha256:9b1afb1631e6c8425c97f3b02fa29d87f0f55bc09bf17cf662910665955da215
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/k_wall/strimzi-operator@sha256:9b1afb1631e6c8425c97f3b02fa29d87f0f55bc09bf17cf662910665955da215
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/k_wall/strimzi-operator@sha256:9b1afb1631e6c8425c97f3b02fa29d87f0f55bc09bf17cf662910665955da215
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge:0.19.0
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans:0.23.0
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor:0.23.0
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
  strategy:
    type: Recreate
