apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/mk-ci-cd/strimzi-operator@sha256:5d214442a1fd84e223976480eb99ab7c29dd2d8fefea4f7dee7e6f885bcb77f2
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              value: "*"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.6.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
                2.7.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.6.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
                2.7.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
              value: |
                2.6.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
                2.7.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.6.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
                2.7.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.6.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
                2.7.0=quay.io/mk-ci-cd/kafka-27@sha256:4490251a47a0e3efc472cb9416fb8234022dd6951145f6cd851f10956a0483c3
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/mk-ci-cd/strimzi-operator@sha256:5d214442a1fd84e223976480eb99ab7c29dd2d8fefea4f7dee7e6f885bcb77f2
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/mk-ci-cd/strimzi-operator@sha256:5d214442a1fd84e223976480eb99ab7c29dd2d8fefea4f7dee7e6f885bcb77f2
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/mk-ci-cd/strimzi-operator@sha256:5d214442a1fd84e223976480eb99ab7c29dd2d8fefea4f7dee7e6f885bcb77f2
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge:0.19.0
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans:0.22.1
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor:0.22.1
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
  strategy:
    type: Recreate
