---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mas-sso
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: mas-sso-operator-catalog
  spec:
    sourceType: grpc
    image: ${IMAGE}:${IMAGE_TAG}
    displayName: MAS SSO
    publisher: MAS Security Team
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: mas-sso-operator
  spec:
    channel: ${CHANNEL}
    name: mas-sso-operator
    source: mas-sso-operator-catalog
    sourceNamespace: ${NAMESPACE}
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: mas-sso-operator
    namespace: ${NAMESPACE}
  spec:
    targetNamespaces:
    - ${NAMESPACE}

parameters:
- name: IMAGE
  value: quay.io/rhoas/mas-sso-operator-catalog
  displayName: mas-sso-operator catalog image
  description: the image of the mas-sso-operator catalog to deploy
  required: true
- name: IMAGE_TAG
  value: "latest"
  displayName: mas-sso-operator catalog version
  description: the version of the mas-sso-operator catalog to deploy
  required: true
- name: NAMESPACE
  value: "saas-deployment-mas-sso"
  displayName: namespace to deploy into
  description: the namespace to deploy into
  required: true
- name: CHANNEL
  value: "alpha"     
  displayName: OLM subscription channel
  description: OLM subscription channel
  required: true
- name: OPERATOR_NAME
  value: "mas-sso-operator"     
  displayName: Operator name for mas-sso operator
  description: Operator name for mas-sso operator
  required: true
- name: RHSSO_OPERATOR_IMAGE
  value: "quay.io/rhoas/rhsso-operator"     
  displayName: Image for RHSSO init container
  description: Image for RHSSO init continer
  required: true
- name: RHSSO_OPERATOR_IMAGE_TAG
  value: "rh-sso-operator-c84f5f1"     
  displayName: Image tag for RHSSO init container
  description: Image tag RHSSO init container
  required: true
- name: RELATED_IMAGE_RHSSO
  value: "quay.io/rhoas/rhsso"     
  displayName: Image for RHSSO
  description: Image for RHSSO
  required: true
- name: RELATED_IMAGE_RHSSO_TAG
  value: "rh-sso-c84f5f1"     
  displayName: Image tag for RHSSO
  description: Image tag RHSSO
  required: true
- name: RELATED_IMAGE_RHSSO_INIT_CONTAINER
  value: "quay.io/rhoas/rhsso-init-container"     
  displayName: Image for RHSSO init container
  description: Image for RHSSO init continer
  required: true
- name: RELATED_IMAGE_RHSSO_INIT_CONTAINER_TAG
  value: "rh-sso-init-container-c84f5f1"     
  displayName: Image tag for RHSSO init container
  description: Image tag RHSSO init container
  required: true
  