---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kas-cluster-owner
parameters:
- name: RH_USERNAME
  required: true
- name: RH_USER_ID
  required: true
- name: RH_ORG_ID
  required: true
objects:
- apiVersion: keycloak.org/v1alpha1
  kind: KeycloakUser
  metadata:
    name: kas-user-${RH_USER_ID}
    labels:
      app: mas-sso
  spec:
    realmSelector:
      matchLabels:
        app: rhoas
    user:
      username: ${RH_USERNAME}
      credentials:
      - type: "password"
        value: "${RH_USERNAME}"
      enabled: True
      clientRoles:
        'realm-management': [ 'view-users' ]
      attributes:
        "account-id": [ "${RH_USER_ID}" ]
        "rh-user-id": [ "${RH_USER_ID}" ]
        "rh-org-id": [ "${RH_ORG_ID}" ]
        "preferred_username": [ "${RH_USERNAME}" ]
      access:
         view: true
         configure: true
         manage: true
