apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedkafkas.managedkafka.bf2.org
spec:
  group: managedkafka.bf2.org
  names:
    kind: ManagedKafka
    plural: managedkafkas
    singular: managedkafka
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              conditions:
                items:
                  properties:
                    type:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                  type: object
                type: array
              capacity:
                properties:
                  ingressEgressThroughputPerSec:
                    anyOf:
                    - type: integer
                    - type: string
                    x-kubernetes-int-or-string: true
                  totalMaxConnections:
                    type: integer
                  maxDataRetentionSize:
                    anyOf:
                    - type: integer
                    - type: string
                    x-kubernetes-int-or-string: true
                  maxPartitions:
                    type: integer
                  maxDataRetentionPeriod:
                    type: string
                  maxConnectionAttemptsPerSec:
                    type: integer
                type: object
              versions:
                properties:
                  kafka:
                    type: string
                  strimzi:
                    type: string
                type: object
              adminServerURI:
                type: string
              updatedTimestamp:
                type: string
            type: object
          spec:
            properties:
              capacity:
                properties:
                  ingressEgressThroughputPerSec:
                    anyOf:
                    - type: integer
                    - type: string
                    x-kubernetes-int-or-string: true
                  totalMaxConnections:
                    type: integer
                  maxDataRetentionSize:
                    anyOf:
                    - type: integer
                    - type: string
                    x-kubernetes-int-or-string: true
                  maxPartitions:
                    type: integer
                  maxDataRetentionPeriod:
                    type: string
                  maxConnectionAttemptsPerSec:
                    type: integer
                type: object
              oauth:
                properties:
                  clientId:
                    type: string
                  clientSecret:
                    type: string
                  tokenEndpointURI:
                    type: string
                  jwksEndpointURI:
                    type: string
                  validIssuerEndpointURI:
                    type: string
                  userNameClaim:
                    type: string
                  tlsTrustedCertificate:
                    type: string
                  customClaimCheck:
                    type: string
                type: object
              endpoint:
                properties:
                  bootstrapServerHost:
                    type: string
                  tls:
                    properties:
                      cert:
                        type: string
                      key:
                        type: string
                    type: object
                type: object
              versions:
                properties:
                  kafka:
                    type: string
                  strimzi:
                    type: string
                type: object
              deleted:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
